# Gradient Descent
- 批量梯度下降 (GD)：
    - 發展背景：這是最基本的梯度下降方法，使用整個訓練集來計算梯度並更新參數。
    - 優點：每次更新都使用所有數據，能夠穩定地收斂到全局最小值。
    - 缺點：計算量大，對於大型數據集來說，計算效率低，內存需求高。
- 隨機梯度下降 (SGD)：
    - 發展背景：為了加速訓練過程，SGD 每次使用一個樣本來計算梯度並更新參數。
    - 優點：計算速度快，內存需求低，能夠快速更新參數。
    - 缺點：更新過程中波動較大，可能會導致收斂到局部最小值。
- Mini-Batch 隨機梯度下降 (Mini-Batch SGD)：
    - 發展背景：這是一種折衷方法，每次使用一小批樣本來計算梯度並更新參數。
    - 優點：結合了 GD 和 SGD 的優點，計算效率高，收斂速度快，波動較小。
    - 缺點：需要選擇合適的批量大小，可能需要調參。
- Momentum：
    - 發展背景：為了加速收斂並減少震盪，Momentum 方法在更新參數時考慮了之前梯度的累積。
    - 優點：能夠加速收斂，減少震盪，特別是在深度學習中效果顯著。
    - 缺點：需要調整動量參數，對於不同問題可能需要不同的參數設置。
- Adagrad：
    - 發展背景：這是一種自適應學習率的方法，根據參數的歷史梯度平方和來調整學習率。
    - 優點：自適應學習率，對於稀疏數據和高維數據效果好，無需手動調整學習率。
    - 缺點：累積梯度平方和會不斷增大，導致學習率過快下降，後期收斂變慢。
- RMSProp：
    - 發展背景：這是對 Adagrad 的改進，使用指數加權平均來計算梯度平方和，從而避免學習率過快下降的問題。
    - 優點：能夠穩定學習率，適應不同問題，收斂速度快。
    - 缺點：需要調整指數加權平均參數，對於不同問題可能需要不同的參數設置。
- Adam：
    - 發展背景：這是目前最流行的優化算法之一，結合了 Momentum 和 RMSProp 的優點，使用一階矩估計和二階矩估計來調整學習率。
    - 優點：自適應學習率，收斂速度快，適應性強，無需大量調參。
    - 缺點：計算量稍大，對於某些問題可能會過擬合。

## Import packages

In [43]:
# pip install scikit-learn

In [6]:
from sklearn.datasets import make_regression
import numpy as np

In [5]:
X, y = make_regression(n_samples=500, n_features=5, noise=1, random_state=42)
X

array([[ 0.56091945, -0.37001103, -0.29548032, -0.25879606,  1.59864717],
       [-1.02438764, -0.92693047, -0.25256815, -0.05952536, -3.24126734],
       [-2.65096981,  0.10643023,  1.09150685, -0.25497722,  1.50399299],
       ...,
       [ 0.05820872,  0.38531738, -1.1429703 , -0.88385744,  0.15372511],
       [ 0.03200415,  0.29929258, -0.75341787,  1.30174129,  1.5615112 ],
       [-1.363174  , -1.59812435,  0.18970617,  0.46217267,  2.02430962]],
      shape=(500, 5))

In [103]:
# 超參數
learning_rate = 0.01
n_iter = 1000
batch_size = 2
epsilon = 1e-8
beta1 = 0.9
beta2 = 0.999
w = np.zeros(X.shape[1])

## Gradient Descent

In [104]:
def gradient_descent(X, y, w, learning_rate, n_iter):
    m = len(y)
    loss_history = []

    for i in range(n_iter):
        gradient = (1/m) * X.T.dot(X.dot(w) - y)
        w -= learning_rate * gradient

        loss = (1/(2*m)) * np.sum((X.dot(w) - y)**2)
        loss_history.append(loss)
    return w, loss_history


In [105]:
gradient_descent(X, y, w, learning_rate, n_iter)

(array([28.90254482, 81.42221227, 30.98890799, 68.52959125, 11.01047064]),
 [np.float64(6449.26746621552),
  np.float64(6320.792630794765),
  np.float64(6194.8967172451785),
  np.float64(6071.527573481497),
  np.float64(5950.634109674677),
  np.float64(5832.166276464635),
  np.float64(5716.07504362284),
  np.float64(5602.312379155406),
  np.float64(5490.83122883754),
  np.float64(5381.5854961703735),
  np.float64(5274.530022751408),
  np.float64(5169.620569049993),
  np.float64(5066.813795579416),
  np.float64(4966.067244457376),
  np.float64(4867.339321346761),
  np.float64(4770.589277768875),
  np.float64(4675.777193781331),
  np.float64(4582.863961013093),
  np.float64(4491.811266049214),
  np.float64(4402.581574158054),
  np.float64(4315.1381133538325),
  np.float64(4229.444858787602),
  np.float64(4145.466517459797),
  np.float64(4063.168513247713),
  np.float64(3982.5169722413757),
  np.float64(3903.4787083814044),
  np.float64(3826.02120939262),
  np.float64(3750.112623007264),


## Stochastic Gradient Descent

In [ ]:
def stochastic_gradient_descent(X, y, w, learning_rate, n_iter):
    m = len(y)
    loss_history = []
    for i in range(n_iter):
        for j in range(m):
            idx = np.random.randint(m)
            X_i = X[idx, :].reshape(1, -1)
            y_i = y[idx].reshape(1, -1)
            gradient = X_i.T.dot(X_i.dot(w) - y_i)
            w -= learning_rate * gradient.flatten()
        # 在每次主要迭代後計算損失
        loss = (1/(2*m)) * np.sum((X.dot(w) - y)**2)
        loss_history.append(loss)
    return w

In [86]:
stochastic_gradient_descent(X, y, w, learning_rate, n_iter)

array([29.04751391, 81.42585867, 30.94073874, 68.51940554, 11.11128392])

## Mini-Batch SGD

In [ ]:
def mini_batch_gradient_descent(X, y, w, learning_rate, n_iter, batch_size):
    m = len(y)
    loss_history = []

    for i in range(n_iter):
        indices = np.random.permutation(m)
        X_shuffled = X[indices]
        y_shuffled = y[indices]
        for j in range(0, m, batch_size):
            X_batch = X_shuffled[j:j+batch_size]
            y_batch = y_shuffled[j:j+batch_size]
            gradient = (1/batch_size) * X_batch.T.dot(X_batch.dot(w) - y_batch)
            w -= learning_rate * gradient
        loss = (1/(2*m)) * np.sum((X.dot(w) - y)**2)
        loss_history.append(loss)
    return w

In [88]:
mini_batch_gradient_descent(X, y, w, learning_rate, n_iter, batch_size)

array([28.89173273, 81.46757769, 30.9878382 , 68.55355005, 11.01100897])

## Momentum

In [ ]:
def momentum(X, y, w, learning_rate, n_iter, beta=0.9):
    m = len(y)
    v = np.zeros(w.shape)
    loss_history = []

    for i in range(n_iter):
        gradient = (1/m) * X.T.dot(X.dot(w) - y)
        v = beta * v + (1 - beta) * gradient
        w -= learning_rate * v
        loss = (1/(2*m)) * np.sum((X.dot(w) - y)**2)
        loss_history.append(loss)
    return w

In [90]:
momentum(X, y, w, learning_rate, n_iter, beta=0.9)

array([28.90714803, 81.42914492, 30.99162161, 68.5315787 , 11.00639857])

## Adagrad
$$ \theta_{t+1} = \theta_t - \frac{\eta}{\sqrt{G_{t,ii} + \epsilon}} \cdot g_t $$

In [ ]:
def adagrad(X, y, w, learning_rate, n_iter, epsilon=1e-8):
    m = len(y)
    G = np.zeros(w.shape)
    loss_history = []
    for i in range(n_iter):
        gradient = (1/m) * X.T.dot(X.dot(w) - y)
        G += gradient ** 2
        adjusted_learning_rate = learning_rate / (np.sqrt(G) + epsilon)
        w -= adjusted_learning_rate * gradient
        loss = (1/(2*m)) * np.sum((X.dot(w) - y)**2)
        loss_history.append(loss)
    return w

In [96]:
adagrad(X, y, w, learning_rate, n_iter, epsilon)

array([28.90714904, 81.42914327, 30.9916216 , 68.53157882, 11.00639958])

## RMSProp

In [ ]:
def rmsprop(X, y, w, learning_rate, n_iter, beta=0.9, epsilon=1e-8):
    m = len(y)
    E_g2 = np.zeros(w.shape)
    loss_history = []
    for i in range(n_iter):
        gradient = (1/m) * X.T.dot(X.dot(w) - y)
        E_g2 = beta * E_g2 + (1 - beta) * gradient ** 2
        adjusted_learning_rate = learning_rate / (np.sqrt(E_g2) + epsilon)
        w -= adjusted_learning_rate * gradient
        loss = (1/(2*m)) * np.sum((X.dot(w) - y)**2)
        loss_history.append(loss)
    return w

## Adam

In [ ]:
def adam(X, y, w, learning_rate, n_iter, beta1=0.9, beta2=0.999, epsilon=1e-8):
    m = len(y)
    m_t = np.zeros(w.shape)
    v_t = np.zeros(w.shape)
    loss_history = []

    for i in range(n_iter):
        gradient = (1/m) * X.T.dot(X.dot(w) - y)
        m_t = beta1 * m_t + (1 - beta1) * gradient
        v_t = beta2 * v_t + (1 - beta2) * gradient ** 2
        m_t_hat = m_t / (1 - beta1 ** (i + 1))
        v_t_hat = v_t / (1 - beta2 ** (i + 1))
        w -= learning_rate * m_t_hat / (np.sqrt(v_t_hat) + epsilon)
        
        # 計算並記錄損失
        loss = (1/(2*m)) * np.sum((X.dot(w) - y)**2)
        loss_history.append(loss)
    return w, loss_history

In [100]:
adam(X, y, w, learning_rate, n_iter, beta1=0.9, beta2=0.999, epsilon=1e-8)

array([28.90714904, 81.42914327, 30.9916216 , 68.53157882, 11.00639958])

In [ ]:
# 執行不同的梯度下降方法
w_gd, loss_history_gd = gradient_descent(X, y, w.copy(), learning_rate=0.01, n_iter=1000)
w_sgd, loss_history_sgd = stochastic_gradient_descent(X, y, w.copy(), learning_rate=0.01, n_iter=1000)
w_mini_batch, loss_history_mini_batch = mini_batch_gradient_descent(X, y, w.copy(), learning_rate=0.01, n_iter=1000, batch_size=2)
w_momentum, loss_history_momentum = momentum(X, y, w.copy(), learning_rate=0.01, n_iter=1000)
w_adagrad, loss_history_adagrad = adagrad(X, y, w.copy(), learning_rate=0.01, n_iter=1000)
w_rmsprop, loss_history_rmsprop = rmsprop(X, y, w.copy(), learning_rate=0.01, n_iter=1000)
w_adam, loss_history_adam = adam(X, y, w.copy(), learning_rate=0.01, n_iter=1000)